# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('asn', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='asn',
        ),
        migrations.AddField(
            model_name='user',
            name='isp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Isp'),
            preserve_default=False,
        ),
    ]
