Vagrant.configure(2) do |config|
  config.vbguest.auto_update = false

  config.vm.define "eos1" do |eos1|
    eos1.vm.box = "vEOS-lab-4.16.6M"
    eos1.vm.network :forwarded_port, guest: 443, host: 12443, id: 'https'

    eos1.vm.network "private_network", virtualbox__intnet: "link_1", ip: "169.254.1.11", auto_config: false
  end

  config.vm.define "eos2" do |eos2|
    eos2.vm.box = "vEOS-lab-4.16.6M"
    eos2.vm.network :forwarded_port, guest: 443, host: 12444, id: 'https'

    eos2.vm.network "private_network", virtualbox__intnet: "link_1", ip: "169.254.1.11", auto_config: false
  end

end
